### ISSUE TITLE
Need GKE model view of looker

### ISSUE THREAD

**Issue by pravargauba** [teamdatatonic/looker-gcp-control#13]
Hi Team,

Just wanted to know if there is any GKE model view of looker ML. We are exploring Looker as an alternative that would connect to our GKE metering usage BQ dataset, so that we can build dashboards on the top of it. We have already explored GCP Billing part. Let me know if there is any datatonic template for GKE as well.

Thanks.

**Comment by jamiefry-datatonic** [comment]
we have no plans at this time to add other services to the open sourced block. Mostly because alot of services are dependent on how you have set up your resources.
a full list of service that can be output to Bigquery and joined up to this model are here
https://cloud.google.com/logging/docs/audit/services
