### ISSUE TITLE
Support the newer BigQueryAuditMetadata format

### ISSUE THREAD

**Issue by pietrodn** [teamdatatonic/looker-gcp-control#8]
Google [introduced a new format](https://cloud.google.com/bigquery/docs/reference/auditlogs/#message_formats) for audit logs: the `BigQueryAuditMetadata` as opposed to the older `AuditData` format which is supported by the model of this block.

Google recommends to use the new format.
Please note that the table names used by the log sink when exporting the new logs and the old logs are the same (but the schema is different!), so if you want to keep both you will need to use separate datasets. :-(

**Comment by jamiefry-datatonic** [comment]
thanks we are aware of this and have it on our to do list. It's not likely we will get a fix our till April (sprints full till then). if anyone has updated the schema to match to the new one, please submit a pull request. thanks!

**Comment by jamiefry-datatonic** [comment]
this has been resolved. Repo patched

**Comment by pietrodn** [comment]
The merged PR does a different thing: it still supports the old `AuditData` format, but as partitioned tables instead of sharded tables.

Indeed, both formats can be written by BigQuery into sharded or partitioned tables.
The two format actually have differing events and column names. See the [documentation](https://cloud.google.com/bigquery/docs/reference/auditlogs/#querying_exported_logs) for the query examples.

**Comment by jamiefry-datatonic** [comment]
I did a check and it looked like the new format had additions to the tables, but did not remove any of the pre existing fields. Please let me know if you think this is incorrect and I will recheck. If correct then the patch supports the new schema but it doesnt model the additions in the lookml. 
The patch is also updating how the sinks are created, as the old sink broke the model.

**Comment by jamiefry-datatonic** [comment]
just to clarify what we have done. We have actually unioned both schemas. So you don't need to create new tables for each. 

protopayload_auditlog.metadataJson is a column in the new schema, which contains a JSON string. In this is the totalBilledBytes, where as in the old schema totalBilledBytes is the following column:
protopayload_auditlog.servicedata_v1_bigquery.jobCompletedEvent.job.jobStatistics.totalBilledBytes

Both are present in the new sink we set up (see readme) so you can take either in the lookml model. Because we have filters applied in the prebuild dashboards when using row counts, we are not double counting.

**Comment by pietrodn** [comment]
Ah, wow. Amazing work, thank you. 🎉 
So if I export just the logs in the newest format, the model should work, right?

**Comment by jamiefry-datatonic** [comment]
Our new sink export pulls in both the AuditData and BigQueryAuditMetadata logs. AuditData is the older version of the logs, and BigQueryAuditMetadata is the new which ADDS new columns. These are therefore unioned in the table. The lookml model pulls from the older version columns, but you have the ability to model the new columns into the model should you wish.

So if you set up a new sink as described in the updated readme, you will have both logs, and the model will not break, and you will also be able to add to the model the new fields should you wish.

However, i just noticed the new schema did remove some fields (the data is still there, its just stored differently). e.g. totalBilledBytes is moved into a nested JSON string, rather than sitting in its own nested record.. luckily this doesnt impact our current model because you can still get this data from the old schema columns which we are mapped too. But it does mean you cannot just export the new schema and export our Lookml to work out of the box, Sorry! 

If you just set up a sink to BigQueryAuditMetadata only the lookml would break.

**Comment by pietrodn** [comment]
Thank you for the clarification. 🙂
